lib/coopagenda_web/router.ex
defmodule CoopagendaWeb.Router do
  use CoopagendaWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug CoopagendaWeb.Plugs.SetUser
  end

  scope "/api", CoopagendaWeb do
    pipe_through :api

    resources "/users", UserController
    resources "/slots", SlotController
    resources "/proposals", ProposalController
  end

  scope "/auth", CoopagendaWeb do
    pipe_through :api

    get "/:provider/callback", AuthController, :callback
    get "/signout", AuthController, :signout
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: CoopagendaWeb.Telemetry
    end
  end

  scope "/", CoopagendaWeb do
    pipe_through :browser

    get "/*path", PageController, :index
  end
end

lib/coopagenda/agenda/slot.ex
defmodule Coopagenda.Agenda.Slot do
  use Ecto.Schema
  import Ecto.Changeset

  @required_fields [:begin, :duration]
  @optional_fields []

  schema "slots" do
    field :begin, :utc_datetime
    field :duration, :integer

    belongs_to :user, Coopagenda.Accounts.User
    many_to_many(:proposals, Coopagenda.Agenda.Proposal, join_through: "slot_proposal", on_replace: :delete)

    timestamps()
  end

  @doc false
  def changeset(slot, attrs) do
    slot
    |> cast(attrs, @optional_fields ++ @required_fields)
    |> validate_required(@required_fields)
  end

  def changeset_update_proposals(slot, proposals) do
    slot
    |> cast(%{}, @optional_fields ++ @required_fields)
    |> put_assoc(:proposals, proposals)
  end
end

lib/coopagenda_web/controllers/slot_controller.ex
defmodule CoopagendaWeb.SlotController do
  use CoopagendaWeb, :controller

  plug :require_admin when action in [:create, :update, :delete]

  alias Coopagenda.Agenda
  alias Coopagenda.Agenda.Slot

  action_fallback CoopagendaWeb.FallbackController

  def index(conn, _params, _user) do
    slots = Agenda.list_slots()
    render(conn, "index.json", slots: slots)
  end

  def create(conn, %{"slot" => slot_params}, _user) do
    with {:ok, %Slot{} = slot} <- Agenda.create_slot(slot_params) do
      conn
      |> put_status(:created)
      |> put_resp_header("location", Routes.slot_path(conn, :show, slot))
      |> render("show.json", slot: slot)
    end
  end

  def show(conn, %{"id" => id}, _user) do
    slot = Agenda.get_slot!(id)
    render(conn, "show.json", slot: slot)
  end

  def update(conn, %{"id" => id, "slot" => slot_params}, _user) do
    slot = Agenda.get_slot!(id)

    with {:ok, %Slot{} = slot} <- Agenda.update_slot(slot, slot_params) do
      render(conn, "show.json", slot: slot)
    end
  end

  def delete(conn, %{"id" => id}, _user) do
    slot = Agenda.get_slot!(id)

    with {:ok, %Slot{}} <- Agenda.delete_slot(slot) do
      send_resp(conn, :no_content, "")
    end
  end

  def action(conn, _) do
    apply(__MODULE__, action_name(conn),
        [conn, conn.params, conn.assigns.user])
  end
end

lib/coopagenda_web/views/slot_view.ex
defmodule CoopagendaWeb.SlotView do
  use CoopagendaWeb, :view
  alias CoopagendaWeb.SlotView
  alias CoopagendaWeb.ProposalView

  def render("index.json", %{slots: slots}) do
    %{data: render_many(slots, SlotView, "slot.json")}
  end

  def render("show.json", %{slot: slot}) do
    %{data: render_one(slot, SlotView, "slot.json")}
  end

  def render("slot.json", %{slot: slot}) do
    %{
      id: slot.id,
      user_id: slot.user_id,
      begin: slot.begin,
      duration: slot.duration,
      proposals: render_many(slot.proposals, ProposalView, "proposal.json")
    }
  end
end

lib/coopagenda_web/templates/slot/index.html.eex
<h1>Listing Slots</h1>

<table>
  <thead>
    <tr>
      <th>Begin</th>
      <th>Duration</th>

      <th>Proposals</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <%= for slot <- @slots do %>
    <tr>
      <td>
        <%= slot.begin |> Timex.format!("%A %d %b %Y at %H:%M (%Z)", :strftime) %>
      </td>
      <td>
        <%= Timex.Duration.from_minutes(slot.duration) |> Timex.Format.Duration.Formatters.Humanized.format %>
      </td>

      <td>
        <ul>
        <%= for proposal <- slot.proposals do %>
          <li>
            <%= proposal.title %>
          </li>
        <% end %>
        </ul>
      </td>

      <td>
        <span><%= link "Show", to: Routes.slot_path(@conn, :show, slot) %></span>
        <%= if @conn.assigns.user != nil do %>
          <%= if @conn.assigns.user.id == slot.user_id do %>
            <span><%= link "Edit", to: Routes.slot_path(@conn, :edit, slot) %></span>
            <span><%= link "Delete", to: Routes.slot_path(@conn, :delete, slot), method: :delete, data: [confirm: "Are you sure?"] %></span>
          <% end %>
        <% end %>
      </td>

      <td>
        <%= if @conn.assigns.user != nil do %>
          <span><%= link "Add a Proposal for this slot", to: Routes.slot_proposal_path(@conn, :new, slot) %></span>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= if @conn.assigns.user != nil and @conn.assigns.user.admin do %>
  <span><%= link "New Slot", to: Routes.slot_path(@conn, :new) %></span>
<% end %>